### ISSUE TITLE
Shape of flat file

### ISSUE THREAD

**Issue by ghzb** [spcnvdr/climatic#3]
I suggested earlier via email that a flat file would be useful for exporting and sharing temperature data. I suggest that the standard CSV format is used.

I suggest the columns are the following:
- Timestamp in YYYY-MM-DD hh:mm:ss format.
- Temperature in Fahrenheit
- Temperature in Celsius

What do you think? Should there be any extra data?

**Comment by spcnvdr** [comment]
There will need to be extra data, specifically relative humidity which must be calculated I believe. I will have to look at my previous test code that used the DHT11 sensor with Python on the RPi. I will send you more details as soon as I have them.

**Comment by ghzb** [comment]
I mentioned in https://github.com/spcnvdr/climatic/issues/5 that using sqlite may be the better option. 

For this issue, we would not need to worry about the shape of the data because columns could be added and deleted as needed.

**Comment by spcnvdr** [comment]
We do not need to change the data format randomly and we are still developing so changing th format will be relatively simple. I do not think we need more than the following data:
we can always convert from C to F if we need to, but we do not need to store both. Same goes for the unit of measurement used by humidity. 

date, time, temperature in C, humidity

**Comment by ghzb** [comment]
Alright I will use the following column names in the CSV

- date
- time
- temp_c
- humidity
