### ISSUE TITLE
How will the flat file be used in the final product?

### ISSUE THREAD

**Issue by ghzb** [spcnvdr/climatic#5]
There are a few ways that the Pi could save data to the flat file. What functionality is needed for the final product?

1. One flat file that is continuously appended with new sensor data
2. Multiple flat files separated by date and appended with new sensor data. For example a flat file for each month.

Additionally how will the file be accessed? 
Will the user have easy access the CSV files through the filesystem or will they be required to interface with the website first?

**Comment by spcnvdr** [comment]
I was thinking there would be a single flat, CSV file which is continuously written to and saved by a daemon written in Python 3 and using WiringPi to interface with the DHT11 sensor. When can make the file automatically roll over after a certain time period or amount of data has been written, but this is an extra feature that we should not worry about right now. The file should be available to be downloaded directly from the web interface, which will probably require some file locks in the daemon to prevent corruption. The user can then manipulate the data manually, open the CSV file in Excel, import into an SQL database, OR upload to the web page which parses the CSV file uploaded by the user ad displays statistics regarding the data (highest temp. seen, lowest temp seen, lowest humidity, dew point, etc.). The calculated statistics are not saved by the website and are only temporary. 

The user can access the CSV file via the file system if they want, but the ideal way will be through downloading from the web site.  Maybe a static link that always points to the CSV file made by the daemon. The location of the master file could be stored in a constant and modified as needed for configuration. As always, this stuff is subject to change as we create new ideas and directions for our project Zeb. Thanks for all your hard work. Let me know what you think.

**Comment by ghzb** [comment]
I forgot about file locking. It would most likely be an issue if a daemon is routinely appending the file.

Maybe it would be better to use SQLite for storing data. SQLite only allows one writer, but it allows multiple simultaneous readers. Data could be queried and a CSV file could be rendered on the fly if at all. 

In general, data would also be easier to query because we do not need to parse the CSV file every time. 

A database could be used too, I just worried that a pi will have performance issues while running a daemon, a web server, and a database server.

**Comment by ghzb** [comment]
That works for me. We'll just have to be extra careful about file locking.
